db:
  image: ursa/postgres:9.5
  environment:
    POSTGRES_USER: odoo
    POSTGRES_PASSWORD: odoo
  volumes:
    - data:/var/lib/postgresql/data/

odoo:
  image: odoo
  links:
    - db:db
  ports:
    - "8069:8069"
    - "8072:8072"
  volumes:
    - extra-addons:/opt/odoo/custom-addons
  command: --

nginx:
  image: nginx
  links:
    - odoo:odoo
  ports:
    - "80:80"
    - "443:443"